### ISSUE TITLE
Fixing building segmentation

### ISSUE THREAD

**Issue by balazsbalint7** [balazsbalint7/building-detection#8]
Check these options, and use these to check if the window containing a tree:

- planar surface detection
- normal vector calculation
- megnézni sorokra, oszlopokra hogy egyezik e a magasság, ha igen, elég csak a középső elemekre megnézni a vector

**Comment by balazsbalint7** [comment]
Maybe this would be the answer:
https://www.geeksforgeeks.org/program-check-three-points-collinear/

**Comment by diana-y29** [comment]
Collinear Points in 3D explanation:
https://www.youtube.com/watch?v=UDt9M8_zxlw
